### ISSUE TITLE
Setting feed: true on listings and for blog does not result in index.xml file for RSS feed

### ISSUE THREAD

**Issue by larnsce** [openwashdata/website#17]
I have followed these instructions:

https://quarto.org/docs/websites/website-blog.html#rss-feed

The index.xml does not show up after rendering the index.qmd of the blog or building the site.

**_quarto.yml**

```
website:
  title: "openwashdata"
  site-url: https://openwashdata.org/
  description: "Website of the openwashdata community"
```

**index.qmd in website/pages/blog**

```
---
title: openwashdata blog
subtitle:
    Stories, tutorials, and tips from and for the openwashdata community
listing:
  sort: "date desc"
  contents: "posts/*/index.qmd"
  type: default
  fields: [image, date, title, author, description, reading-time]
  sort-ui: false
  filter-ui: false
  categories: true
  feed: true
```
